# Base image
ARG UBUNTU_VERSION=20.04
ARG NVIDIA_CUDA_VERSION=11.4.1
FROM nvidia/cudagl:${NVIDIA_CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}

# Install basic packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    build-essential git wget curl zip unzip unrar \
    vim cmake ca-certificates \
    libopengl-dev libjpeg-dev libpng-dev \
    libglfw3-dev libglm-dev libx11-dev libomp-dev \
    libegl1-mesa-dev libglib2.0-0 pkg-config && \
    rm -rf /var/lib/apt/lists/*

# Install Miniconda
ENV CONDA_DIR=/opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    bash ~/miniconda.sh -b -p $CONDA_DIR && \
    rm ~/miniconda.sh
ENV PATH=$CONDA_DIR/bin:$PATH

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

# Create conda environment
RUN conda create -y -n habitat python=3.9 cmake=3.14.0 && \
    conda clean -afy

# Activate environment and install habitat-sim
RUN git clone https://github.com/facebookresearch/habitat-sim.git -b v0.2.4 && cd habitat-sim && \
    conda run -n habitat pip install --no-cache-dir -r requirements.txt && \
    conda run -n habitat python setup.py install --headless --with-cuda

# Install habitat-lab, not include habitat-baseline
RUN git clone https://github.com/facebookresearch/habitat-lab.git -b v0.2.4 && cd habitat-lab && \
    conda run -n habitat pip install -e habitat-lab && \
    conda run -n habitat pip install -e habitat-baselines

# Install pytorch, refer[https://pytorch.org/get-started/previous-versions/]
RUN conda install -n habitat pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch

# Set default shell to bash and activate environment
SHELL ["/bin/bash", "-c"]
ENV PATH=$CONDA_DIR/envs/habitat/bin:$PATH


## 
#
#RUN conda install cudatoolkit==11.0.221 
#RUN pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 -f https://download.pytorch.org/whl/cu110/torch_stable.html
#
##[install detectron2]
#RUN python -m pip install 'git+https://github.com/facebookresearch/detectron2.git@v0.5'
#
##[install L3MVN]
#RUN git clone https://github.com/ybgdgh/L3MVN.git
## remove broken dependency
#RUN cd L3MVN/ && sed -i "1d" requirements.txt &&  pip install -r requirements.txt
#RUN pip install scikit-fmm gdown
##[download segmentation model]
#RUN mkdir /root/L3MVN/RedNet/model/
#RUN gdown --fuzzy https://drive.google.com/file/d/1U0dS44DIPZ22nTjw0RfO431zV-lMPcvv/view?usp=share_link -O /root/L3MVN/RedNet/model/
#
#
#
#
## Setup habitat-sim
#RUN git clone --branch stable https://github.com/facebookresearch/habitat-sim.git
#RUN /bin/bash -c ". activate habitat; cd habitat-sim; pip install -r requirements.txt; python setup.py install --headless"
#
## Install challenge specific habitat-lab
#RUN git clone --branch stable https://github.com/facebookresearch/habitat-lab.git
#RUN /bin/bash -c ". activate habitat; cd habitat-lab; pip install -e ."
#
## Silence habitat-sim logs
#ENV GLOG_minloglevel=2
#ENV MAGNUM_LOG="quiet"
